sudo: false

language: node_js
node_js:
  - "0.12.2"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.8

notifications:
  slack: slackerspace:LtstVlXCibPekCBpSTfP2DDI

install:
  - npm config set registry https://registry.npmjs.org/
  - npm install -g gulp bower cordova ionic
  - npm install
  - bower update

before_script:
  - wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
  - tar -xvf android-sdk_r24.4-linux.tgz
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-23.0.2
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-23
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2

script:
  - ionic platform remove android
  - ionic platform add android
  - ionic resources --icon
  - ionic build android

deploy:
  provider: heroku
  app: btb-ionic
  api_key:
    secure: HsFim87ssnudS6L1uvDa+i9fSZdiphYYz6HLvGGWtYzlCFmbVEV2Wktsl2RzjVMjytv5vHxwbHboYRdPH2UoOuoNqe1dnX4ZglTA1TKwjiPi9YXanUkP9wykNhwI4PlRFWG3qfU8wzIbb+pYTDokYcY2eM7kzDLGLLxJGBlkSNDVpIm5yWbOqU9SvGqNhqFwJ1+wyB2bgOVE42PI285w+RRZ1DvoN8XTXwK2oAZOSr/NPfA3BcGRNCBBNVA05tJ2Ynzu10CVwgY3kyAaDUz5i5998TtAOFe1PYo5CMamOpNrbN2S4lOp91VO7ZA3GS1AvHgTPHRHhF0ePjlsv3hhmYiZRHwfPQnjZRQVQHTsbFVHeQSjePufrk/eBpOzaxqsW+wNdLSux3fl4v495E67WJoBkSYChikPrtoB4mr7C9LDLkNmSzRw/pfoWh9BgIXJllUFq6NercC/qRG1YGFgmibNDIHdDy/WWyshCYwrOOSoBwKjGhYE7OezMqQBDs/KTybK9mGHUoRaehn1pvEATMdMxyDhV6dEU/cKpZrVfWagQ0oMf9ieoJ5MJOs3cMXCPKGs6w4q6XEqqXUjSAOs55UmVjCCmrPu3P80+9F88XXUl1rPBLO6kdu5Q1YhWyx3CYSmYIxBEDrLzWPsN30vVkC8U5hGrtUTR1RpW2Bv3RU=